# np.array


In [1]:
import numpy as np

In [2]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


In [3]:
np_baseball = np.array(baseball)
print(np_baseball.shape)

# Two ways to select a value from a 2D array
# List does not allow such operation
print(np_baseball[1,1])
print(np_baseball[1][1])

# print(baseball[1][1]) # VALID
# print(baseball[1,1])  # NOT VALID

np_baseball

(4, 2)
102.7
102.7


array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [4]:
# Can think ndarray as multiple columns of values
# Therefore select each single column
# List does not allow such operation
height= np_baseball[:,0]
weight = np_baseball[:,1]

# print(baseball[:,0])


print(height)
print(height.shape)

print(weight)


[180. 215. 210. 188.]
(4,)
[ 78.4 102.7  98.5  75.2]


In [5]:
# mean and median

print(height.mean())
print(np.mean(height))

# print(height.median())    # NO MEDIAN ATTRIBUTE
print(np.median(height))

print(height.std())
print(np.std(height))



198.25
198.25
199.0
14.635146053251399
14.635146053251399


## Multiple logical test

In [7]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])


In [9]:
np.logical_and(my_house<20, my_house<10)

array([False, False, False,  True])